"use client"

import type React from "react"

import { useState, useRef } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Download, Plus, FileDown } from "lucide-react"

interface Invoice {
  id: string
  customerName: string
  amount: number
  date: string
  type: "invoice" | "loc" | "form"
}

export default function InvoiceGenerator() {
  const [formData, setFormData] = useState({ customerName: "", amount: "", docType: "invoice" })
  const [invoices, setInvoices] = useState<Invoice[]>([])
  const printRef = useRef<HTMLDivElement>(null)

  // Load invoices from localStorage
  const handleLoadInvoices = () => {
    const stored = JSON.parse(localStorage.getItem("invoices") || "[]")
    setInvoices(stored)
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!formData.customerName || !formData.amount) return

    const newInvoice: Invoice = {
      id: Date.now().toString(),
      customerName: formData.customerName,
      amount: Number.parseFloat(formData.amount),
      date: new Date().toLocaleDateString(),
      type: formData.docType as "invoice" | "loc" | "form",
    }

    const updated = [...invoices, newInvoice]
    setInvoices(updated)
    localStorage.setItem("invoices", JSON.stringify(updated))
    setFormData({ customerName: "", amount: "", docType: "invoice" })
  }

  const downloadPDF = async (invoice: Invoice) => {
    try {
      // Dynamically import jsPDF and html2canvas
      const { jsPDF } = await import("jspdf")
      const html2canvas = (await import("html2canvas")).default

      // Create a temporary container for PDF content
      const container = document.createElement("div")
      container.innerHTML = `
        <div style="padding: 40px; font-family: Arial, sans-serif; width: 100%; max-width: 800px; background: white;">
          <h1 style="text-align: center; color: #1e40af; margin-bottom: 30px; font-size: 28px;">
            ${invoice.type.toUpperCase()}
          </h1>
          
          <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px;">
            <p style="margin: 10px 0;"><strong>Company Name:</strong> CarFlow Rentals</p>
            <p style="margin: 10px 0;"><strong>Date:</strong> ${invoice.date}</p>
            <p style="margin: 10px 0;"><strong>Document ID:</strong> #${invoice.id}</p>
          </div>

          <div style="margin-bottom: 20px;">
            <p style="margin: 10px 0;"><strong>Customer Name:</strong> ${invoice.customerName}</p>
          </div>

          <div style="border: 1px solid #ddd; padding: 15px; margin-bottom: 20px;">
            <p style="margin: 5px 0;"><strong>Amount:</strong> $${invoice.amount.toFixed(2)}</p>
            <p style="margin: 5px 0;"><strong>Type:</strong> ${invoice.type.toUpperCase()}</p>
          </div>

          <p style="text-align: center; color: #666; font-size: 12px; margin-top: 30px;">
            Generated by CarFlow - Car Rental Management System
          </p>
        </div>
      `

      document.body.appendChild(container)
      const canvas = await html2canvas(container)
      document.body.removeChild(container)

      const pdf = new jsPDF("p", "mm", "a4")
      const imgData = canvas.toDataURL("image/png")
      pdf.addImage(imgData, "PNG", 10, 10, 190, 277)
      pdf.save(`${invoice.type}_${invoice.id}.pdf`)
    } catch (error) {
      console.error("Error generating PDF:", error)
      // Fallback to print if PDF generation fails
      handlePrint(invoice)
    }
  }

  const handlePrint = (invoice: Invoice) => {
    const printContent = `
      <div style="padding: 40px; font-family: Arial, sans-serif; width: 100%; max-width: 800px;">
        <h1 style="text-align: center; color: #1e40af; margin-bottom: 30px;">
          ${invoice.type.toUpperCase()}
        </h1>
        
        <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px;">
          <p style="margin: 10px 0;"><strong>Company Name:</strong> CarFlow Rentals</p>
          <p style="margin: 10px 0;"><strong>Date:</strong> ${invoice.date}</p>
          <p style="margin: 10px 0;"><strong>Document ID:</strong> #${invoice.id}</p>
        </div>

        <div style="margin-bottom: 20px;">
          <p style="margin: 10px 0;"><strong>Customer Name:</strong> ${invoice.customerName}</p>
        </div>

        <div style="border: 1px solid #ddd; padding: 15px; margin-bottom: 20px;">
          <p style="margin: 5px 0;"><strong>Amount:</strong> $${invoice.amount.toFixed(2)}</p>
          <p style="margin: 5px 0;"><strong>Type:</strong> ${invoice.type.toUpperCase()}</p>
        </div>

        <p style="text-align: center; color: #666; font-size: 12px; margin-top: 30px;">
          Generated by CarFlow - Car Rental Management System
        </p>
      </div>
    `

    const printWindow = window.open("", "", "height=600,width=800")
    if (printWindow) {
      printWindow.document.write(printContent)
      printWindow.document.close()
      setTimeout(() => printWindow.print(), 250)
    }
  }

  const handleDelete = (id: string) => {
    const updated = invoices.filter((inv) => inv.id !== id)
    setInvoices(updated)
    localStorage.setItem("invoices", JSON.stringify(updated))
  }

  return (
    <div className="space-y-6">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-foreground mb-2">Invoice Generator</h2>
        <p className="text-muted-foreground">Generate professional PDF documents (Invoice, LOC, or Form)</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="border-border lg:col-span-1">
          <CardHeader>
            <CardTitle>Create Document</CardTitle>
            <CardDescription>Fill in details to generate</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <Label htmlFor="name" className="text-foreground">
                  Customer Name
                </Label>
                <Input
                  id="name"
                  type="text"
                  value={formData.customerName}
                  onChange={(e) => setFormData({ ...formData, customerName: e.target.value })}
                  placeholder="Enter customer name"
                  className="border-border bg-background text-foreground"
                />
              </div>

              <div>
                <Label htmlFor="amount" className="text-foreground">
                  Amount
                </Label>
                <Input
                  id="amount"
                  type="number"
                  step="0.01"
                  value={formData.amount}
                  onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                  placeholder="0.00"
                  className="border-border bg-background text-foreground"
                />
              </div>

              <div>
                <Label htmlFor="type" className="text-foreground">
                  Document Type
                </Label>
                <select
                  id="type"
                  value={formData.docType}
                  onChange={(e) => setFormData({ ...formData, docType: e.target.value })}
                  className="w-full px-3 py-2 border border-border rounded-md bg-background text-foreground"
                >
                  <option value="invoice">Invoice</option>
                  <option value="loc">LOC (Letter of Credit)</option>
                  <option value="form">Form</option>
                </select>
              </div>

              <Button type="submit" className="w-full bg-primary text-primary-foreground hover:bg-primary/90 gap-2">
                <Plus className="w-4 h-4" />
                Generate
              </Button>
            </form>
          </CardContent>
        </Card>

        <Card className="border-border lg:col-span-2">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Generated Documents</CardTitle>
                <CardDescription>{invoices.length} documents created</CardDescription>
              </div>
              <Button onClick={handleLoadInvoices} variant="outline" className="border-border bg-transparent">
                Refresh
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            {invoices.length === 0 ? (
              <p className="text-muted-foreground text-center py-8">No documents generated yet</p>
            ) : (
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {invoices.map((invoice) => (
                  <div
                    key={invoice.id}
                    className="flex items-center justify-between p-3 bg-muted rounded-lg border border-border"
                  >
                    <div className="flex-1">
                      <p className="font-medium text-foreground">{invoice.customerName}</p>
                      <p className="text-sm text-muted-foreground">
                        {invoice.type.toUpperCase()} • ${invoice.amount.toFixed(2)} • {invoice.date}
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        onClick={() => downloadPDF(invoice)}
                        size="sm"
                        className="bg-accent text-accent-foreground hover:bg-accent/90 gap-1"
                      >
                        <FileDown className="w-3 h-3" />
                        PDF
                      </Button>
                      <Button
                        onClick={() => handlePrint(invoice)}
                        size="sm"
                        className="bg-secondary text-secondary-foreground hover:bg-secondary/90 gap-1"
                      >
                        <Download className="w-3 h-3" />
                        Print
                      </Button>
                      <Button
                        onClick={() => handleDelete(invoice.id)}
                        size="sm"
                        variant="outline"
                        className="border-border text-destructive hover:bg-destructive/10"
                      >
                        Delete
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
